sudo: required
dist: trusty
language: python
cache:
  - pip
  - apt

python:
  - 3.6

install:
  - easy_install distribute
  - pip install -r dev_requirements.txt

script:
  - py.test -v
  - python setup.py sdist bdist

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: goA98Su+j5/RKe+KXsGBbyOw5Zu3LOdI9kTSYZtU8hx6TycmfY5cFwcXdBvLGoYNlWDzJSFY2TE4nZutkWs0E2bzIjtdV9NJJbz3ZJ4V56powDwG5m7zOHqKD5hP5p0dNqWka9cgvQa7qSrLFFV/RTXOuy/69tVgBPB5XWxseYHHsCsuY9gwlK+KzIBmNtAvhcWPjks66kvvnDudPDidZGCZa0td4DN/6pxlbAKQWMmdtFqwnWkRKJbl4XexAQyyI9VQ+JLAXLo5WL4TRGuRcSczSk5hvdNr2yG3RLbYsH0y8iijHLDcfmj6xcuy2Cxj7KSZmDnbeLc4KskqqC8pm9zIA8NvrqRnTeRVFLqTFiEXFVNhXXx4k+KkoAdpne3PYp/oJVmtBhQNt5BTm7ZJ4di8P+dnNQC5MKNeB68WaL22AxP1P9FvHcThFeDVMJMPs95FwH3fa+R7C2BRocJPVjMMUDB2W8mfpCC3fAhKTMTUt143VcEv3D6Eix00VGxal7daxVcKU+icR7DYZExJfMmXkFgqhgSZPeoWzxmvBL9xVAAqq3gYG4rxLQtMEeN5Sz8TlIXK95piSy6K85dQETAgUj5aOtZo1OZ+LXuYX+r1WrVX9Gn99U3T47sZ8m1Yr21aD3HBZ8jCE4jWRG2gFgP1/8TTDmyxcFLG0sKKjj8=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
